---
common:
  service_url: https://facade-maint-config-windows-use-ssh-6f3kfepqcq-ew.a.run.app/v1/provision

".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  include_todos: true
appveyor.yml:
  delete: true

Gemfile:
  use_travis: true
  optional:
    ":development":
    - gem: 'ruby-pwsh'
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/ci.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
