---
.travis.yml:
  includes:
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0"
appveyor.yml:
  matrix:
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21-x64
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 23
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 23-x64
Gemfile:
  optional:
    ':development':
      - gem: 'beaker-testmode_switcher'
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
NOTICE:
  copyright_holders:
    - name: 'OpenTable'
      begin: 2012
      end: 2015
    - name: 'Puppet, Inc.'
      begin: 2015

# already using master branch's version
spec/spec_helper.rb:
  unmanaged: true
